# Generated by Django 3.1.6 on 2021-02-28 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FileHandling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('index', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='LanguageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('experience', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='relevantclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SmallProjectBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('index', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('link', models.URLField(max_length=255)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='TerminalText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('shouldDelete', models.BooleanField(default=False)),
                ('newLine', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('dates', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fileText', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FileHandling.resumeimage')),
                ('optionalFile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FileHandling.fileupload')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='LargeProjectBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('link', models.URLField(max_length=255)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FileHandling.projectimage')),
                ('languages', models.ManyToManyField(related_name='LargeProjectBox', to='Components.LanguageItem')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('skills', models.ManyToManyField(related_name='Skills', to='Components.LanguageItem')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('dates', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('coursework', models.ManyToManyField(blank=True, related_name='Education', to='Components.relevantclass')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FileHandling.resumeimage')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
