# Generated by Django 3.1.6 on 2021-02-28 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languageitem',
            options={'ordering': ['-experience']},
        ),
    ]
