# Generated by Django 3.1.6 on 2021-02-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0002_auto_20210228_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageitem',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
