# Generated by Django 3.1.6 on 2021-02-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0004_auto_20210228_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageitem',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
