# Generated by Django 3.1.6 on 2021-02-28 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0005_auto_20210228_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languageitem',
            options={'ordering': ['-experience', '-priority']},
        ),
    ]
