# Generated by Django 3.1.6 on 2021-11-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0006_auto_20210228_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallprojectbox',
            name='displayed',
            field=models.BooleanField(default=True),
        ),
    ]
