# Generated by Django 3.1.6 on 2021-03-05 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='create',
            new_name='created',
        ),
    ]
